services:
  db:
    container_name: "crm"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_test:
    container_name: "crm_test"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DATABASE}
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
  backup:
    container_name: "crm_backup"
    image: postgres:14.1-alpine
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h db -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /backups/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backups/*.dump | head -n -$$MAX_BACKUP_COUNT | xargs rm -f
        sleep $$BACKUP_DELTA
      done"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - BACKUP_DELTA=3600
      - MAX_BACKUP_COUNT=5
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    env_file:
      - .env
  bot:
    container_name: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 bot.py
    volumes:
      - .:/bot
    env_file:
      - .env
volumes:
  pgdata: