services:
  db_test:
    container_name: "crm_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      secrets:
        - secret_key
    ports:
      - "${POSTGRES_TEST_HOST_PORT}:${POSTGRES_TEST_OUTER_PORT}"
volumes:
  pgdata:
secrets:
  secret_key:
    environment: "Tests"