services:
  db:
    container_name: "crm"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm
    ports:
      - "5500:5432"
    networks:
      - custom
  db_test:
    container_name: "crm_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=crm_test
    ports:
      - " :5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge