"""Rename log_data to log in MLog

Revision ID: 09102b64f5d1
Revises: 62f593dddb2a
Create Date: 2024-09-07 16:11:49.368314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09102b64f5d1'
down_revision: Union[str, None] = '62f593dddb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('log', sa.String(), nullable=False))
    op.drop_column('logs', 'log_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('log_data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('logs', 'log')
    # ### end Alembic commands ###
