"""Add ondelete CASCADE to MLog

Revision ID: 56b5d9d35c80
Revises: 1b478a91224c
Create Date: 2024-09-13 09:57:35.951812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b5d9d35c80'
down_revision: Union[str, None] = '1b478a91224c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logs_contact_id_fkey', 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key('logs_contact_id_fkey', 'logs', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###
