"""Change date to datetime in MLog

Revision ID: 6e8d327fa1de
Revises: 597f7c65e017
Create Date: 2024-09-03 13:37:34.050858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8d327fa1de'
down_revision: Union[str, None] = '597f7c65e017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('log', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('log', 'datetime')
    # ### end Alembic commands ###
