"""Remove area from MContact

Revision ID: 1b478a91224c
Revises: f13d50101759
Create Date: 2024-09-13 03:08:47.969326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b478a91224c'
down_revision: Union[str, None] = 'f13d50101759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
