"""Fix auto timestamp to logs

Revision ID: 00458f8f0914
Revises: f756fcb863db
Create Date: 2024-09-15 20:15:36.311820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00458f8f0914'
down_revision: Union[str, None] = 'f756fcb863db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
