"""Fix UUID in MContact

Revision ID: 8974c30d6d25
Revises: d3f36aacae9d
Create Date: 2024-09-03 12:57:14.936607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8974c30d6d25'
down_revision: Union[str, None] = 'd3f36aacae9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
