"""Remove log from MContact

Revision ID: c8ed9f5a748b
Revises: 56b5d9d35c80
Create Date: 2024-09-13 10:25:41.980705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ed9f5a748b'
down_revision: Union[str, None] = '56b5d9d35c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('log', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
